#!/usr/bin/env node
/**
 * Export configurations and session data
 * Makes it easy to share setups and results
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadConfig, discoverConfig } from '../lib/config.js';
import { loadState, findLatestSession } from '../core/state.js';
import { detectGitRepo } from '../lib/git-detect.js';
import type { EchelonConfig, EchelonState } from '../lib/types.js';

export interface ExportOptions {
  type: 'config' | 'session' | 'both';
  sessionId?: string;
  output?: string;
  format?: 'json' | 'yaml' | 'markdown';
}

/**
 * Export configuration to shareable format
 */
export function exportConfig(config: EchelonConfig, format: 'json' | 'yaml' | 'markdown' = 'json'): string {
  if (format === 'json') {
    return JSON.stringify(config, null, 2);
  }

  if (format === 'markdown') {
    return `# Echelon Configuration

## Project
- **Repository:** ${config.project.repo}
- **Base Branch:** ${config.project.baseBranch}

## Budget
- **Total:** $${config.maxTotalBudgetUsd}
- **Approval Mode:** ${config.approvalMode}
- **Billing:** ${config.billing}

## Layers

### 2IC (Second in Command)
- **Model:** ${config.layers['2ic'].model}
- **Budget:** $${config.layers['2ic'].maxBudgetUsd}
- **Max Turns:** ${config.layers['2ic'].maxTurns}

### Engineering Lead
- **Model:** ${config.layers['eng-lead'].model}
- **Budget:** $${config.layers['eng-lead'].maxBudgetUsd}
- **Max Turns:** ${config.layers['eng-lead'].maxTurns}

### Team Lead
- **Model:** ${config.layers['team-lead'].model}
- **Budget:** $${config.layers['team-lead'].maxBudgetUsd}
- **Max Turns:** ${config.layers['team-lead'].maxTurns}

## Engineers
- **Engine:** ${config.engineers.engine}
- **Max Parallel:** ${config.engineers.maxParallel}
- **Create PRs:** ${config.engineers.createPr ? 'Yes' : 'No'}
- **Draft PRs:** ${config.engineers.prDraft ? 'Yes' : 'No'}

---
*Exported from Echelon AI Orchestrator*
*Built by VENIN (George Atkinson & Claude Opus 4.6)*
`;
  }

  // YAML format
  return `# Echelon Configuration
project:
  repo: ${config.project.repo}
  path: ${config.project.path}
  baseBranch: ${config.project.baseBranch}

maxTotalBudgetUsd: ${config.maxTotalBudgetUsd}
approvalMode: ${config.approvalMode}
billing: ${config.billing}

layers:
  2ic:
    model: ${config.layers['2ic'].model}
    maxBudgetUsd: ${config.layers['2ic'].maxBudgetUsd}
    maxTurns: ${config.layers['2ic'].maxTurns}
  eng-lead:
    model: ${config.layers['eng-lead'].model}
    maxBudgetUsd: ${config.layers['eng-lead'].maxBudgetUsd}
    maxTurns: ${config.layers['eng-lead'].maxTurns}
  team-lead:
    model: ${config.layers['team-lead'].model}
    maxBudgetUsd: ${config.layers['team-lead'].maxBudgetUsd}
    maxTurns: ${config.layers['team-lead'].maxTurns}

engineers:
  engine: ${config.engineers.engine}
  maxParallel: ${config.engineers.maxParallel}
  createPr: ${config.engineers.createPr}
  prDraft: ${config.engineers.prDraft}
`;
}

/**
 * Export session data to shareable format
 */
export function exportSession(state: EchelonState, format: 'json' | 'markdown' = 'json'): string {
  if (format === 'json') {
    return JSON.stringify(state, null, 2);
  }

  // Markdown format
  const duration = new Date(state.updatedAt).getTime() - new Date(state.startedAt).getTime();
  const durationMin = Math.floor(duration / 60000);

  return `# Echelon Session Report

## Summary
- **Session ID:** ${state.sessionId}
- **Project:** ${state.projectRepo}
- **Status:** ${state.status}
- **Directive:** ${state.directive}

## Metrics
- **Total Cost:** $${state.totalCost.toFixed(4)}
- **Duration:** ${durationMin} minutes
- **Messages Exchanged:** ${state.messages.length}
- **Issues Created:** ${state.issues.length}
- **Started:** ${new Date(state.startedAt).toLocaleString()}
- **Last Updated:** ${new Date(state.updatedAt).toLocaleString()}

## Agent Performance

${Object.entries(state.agents).map(([role, agent]) => `
### ${role.toUpperCase()}
- **Status:** ${agent.status}
- **Cost:** $${agent.totalCost.toFixed(4)}
- **Turns Completed:** ${agent.turnsCompleted}
${agent.lastError ? `- **Last Error:** ${agent.lastError}` : ''}
`).join('\n')}

## Issues Created

${state.issues.length > 0 ? state.issues.map(issue => `
- [#${issue.number}] ${issue.title}
  - Labels: ${issue.labels.join(', ')}
`).join('\n') : '*No issues created*'}

## Message Flow

${state.messages.slice(0, 10).map((msg, i) => `
${i + 1}. **${msg.from} → ${msg.to || 'system'}**
   ${msg.content.slice(0, 100)}${msg.content.length > 100 ? '...' : ''}
`).join('\n')}

${state.messages.length > 10 ? `\n*... and ${state.messages.length - 10} more messages*\n` : ''}

---
*Generated by Echelon AI Orchestrator*
*Built by VENIN (George Atkinson & Claude Opus 4.6)*
`;
}

/**
 * Run the export command
 */
export async function runExport(options: ExportOptions): Promise<void> {
  const detected = detectGitRepo();
  if (!detected && !options.sessionId) {
    console.error('Error: Not in a git repo. Run from a project directory or specify --session.');
    process.exit(1);
  }

  const format = options.format || 'json';
  const outputBase = options.output || `echelon-export-${Date.now()}`;

  // Export config
  if (options.type === 'config' || options.type === 'both') {
    const configPath = discoverConfig(detected?.path);
    if (!configPath) {
      console.error('Error: No config file found. Run echelon init first.');
      process.exit(1);
    }

    const config = loadConfig(configPath);
    const configExport = exportConfig(config, format);
    const configFile = `${outputBase}-config.${format === 'json' ? 'json' : format === 'yaml' ? 'yml' : 'md'}`;

    writeFileSync(configFile, configExport);
    console.log(`✓ Config exported to: ${configFile}`);
  }

  // Export session
  if (options.type === 'session' || options.type === 'both') {
    const sessionId = options.sessionId || (detected && findLatestSession(detected.repo));
    if (!sessionId) {
      console.error('Error: No session found. Run a cascade first.');
      process.exit(1);
    }

    const state = loadState(sessionId);
    if (!state) {
      console.error(`Error: Could not load session ${sessionId}`);
      process.exit(1);
    }

    const sessionExport = exportSession(state, format === 'yaml' ? 'markdown' : format);
    const sessionFile = `${outputBase}-session.${format === 'json' ? 'json' : 'md'}`;

    writeFileSync(sessionFile, sessionExport);
    console.log(`✓ Session exported to: ${sessionFile}`);
  }

  console.log('\n✓ Export complete!');
}
